basePath: /
definitions:
  types.AudioRequest:
    properties:
      audio:
        type: string
    type: object
  types.AuthRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  types.GetInfoResponse:
    properties:
      task_id:
        type: string
    type: object
  types.GetResultResponse:
    properties:
      result:
        type: string
    type: object
  types.GetStatusResponse:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для преобразования речи в текст
  title: Speech to Text API
  version: "1.0"
paths:
  /audio:
    post:
      consumes:
      - application/json
      description: Отправляет аудио файл для преобразования в текст
      parameters:
      - description: Аудио данные
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AudioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ID задачи создана
          schema:
            $ref: '#/definitions/types.GetInfoResponse'
        "400":
          description: Ошибка валидации
          schema:
            type: string
        "401":
          description: Не авторизован
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Загрузка аудио для обработки
      tags:
      - audio
  /login:
    post:
      consumes:
      - application/json
      description: Авторизует пользователя и создает сессию
      parameters:
      - description: Данные для авторизации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка валидации
          schema:
            type: string
        "401":
          description: Неверные учетные данные
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Авторизация пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя в системе
      parameters:
      - description: Данные для регистрации
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная регистрация
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Ошибка валидации
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - auth
  /result:
    get:
      consumes:
      - application/json
      description: Возвращает результат преобразования аудио в текст
      parameters:
      - description: ID задачи
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.GetInfoResponse'
      produces:
      - application/json
      responses:
        "200":
          description: Результат обработки
          schema:
            $ref: '#/definitions/types.GetResultResponse'
        "400":
          description: Ошибка валидации
          schema:
            type: string
        "401":
          description: Не авторизован
          schema:
            type: string
        "403":
          description: Доступ запрещен
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Получение результата обработки
      tags:
      - tasks
  /status:
    get:
      consumes:
      - application/json
      description: Возвращает текущий статус обработки аудио
      parameters:
      - description: ID задачи
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.GetInfoResponse'
      produces:
      - application/json
      responses:
        "200":
          description: Статус задачи
          schema:
            $ref: '#/definitions/types.GetStatusResponse'
        "400":
          description: Ошибка валидации
          schema:
            type: string
        "401":
          description: Не авторизован
          schema:
            type: string
        "403":
          description: Доступ запрещен
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Получение статуса задачи
      tags:
      - tasks
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
