ALTER TABLE users ADD CONSTRAINT users_username_pk PRIMARY KEY (username);
ALTER TABLE users ALTER COLUMN password TYPE TEXT;

ALTER TABLE tasks ADD CONSTRAINT tasks_task_id_pk PRIMARY KEY (task_id);
ALTER TABLE tasks ALTER COLUMN audio TYPE TEXT;
ALTER TABLE tasks ALTER COLUMN result TYPE TEXT;
ALTER TABLE tasks ALTER COLUMN status TYPE TEXT;
