ALTER TABLE tasks ALTER COLUMN status TYPE VARCHAR(1000);
ALTER TABLE tasks ALTER COLUMN result TYPE VARCHAR(1000);
ALTER TABLE tasks ALTER COLUMN audio TYPE VARCHAR(1000);
ALTER TABLE tasks DROP CONSTRAINT tasks_task_id_pk;

ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(1000);
ALTER TABLE users DROP CONSTRAINT users_username_pk;
